name: Build Workflow

on:
    workflow_call:

permissions:
    id-token: write
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        environment: ${{ inputs.environment }}
        steps:
            -   uses: actions/checkout@v4
            -   uses: actions/setup-java@v4
                with:
                    java-version: '21'
                    distribution: 'corretto'
                    cache: maven
            # See the following for more details - https://stackoverflow.com/questions/61096521/how-to-use-gpg-key-in-github-actions
            -   name: Configure GPG Key
                run: |
                    echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
                env:
                    GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}

            -   name: Maven build
                run: ./mvnw install
