name: Main Workflow

on:
    workflow_call:
        secrets:
            gpg_private_key:
                required: true
            gpg_passphrase:
                required: true
            central_username:
                required: true
            central_password:
                required: true

permissions:
    id-token: write
    contents: write  # Needed for creating tags

jobs:
    build:
        runs-on: ubuntu-latest
        environment: ${{ inputs.environment }}
        steps:
            -   uses: actions/checkout@v4
            -   name: Import GPG Key
                uses: crazy-max/ghaction-import-gpg@v6
                with:
                    gpg_private_key: ${{ secrets.gpg_private_key }}
                    passphrase: ${{ secrets.gpg_passphrase }}
                    git_user_signingkey: true
                    git_commit_gpgsign: true
                    git_tag_gpgsign: true
            -   name: Cache local Maven repository
                uses: actions/cache@v3
                with:
                    path: ~/.m2/repository
                    key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                    restore-keys: |
                        ${{ runner.os }}-maven-
            -   uses: actions/setup-java@v4
                with:
                    java-version: '21'
                    distribution: 'corretto'
                    cache: maven
                    server-id: central  # Matches publishingServerId
                    server-username: MAVEN_USERNAME
                    server-password: MAVEN_PASSWORD
            -   name: Increment version
                id: increment-version
                uses: RichardInnocent/semantic-versioning-maven@v0.1.0
            -   name: Print if version changed
                if: steps.increment-version.outputs.previous-version != steps.increment-version.outputs.new-version
                run: echo "The new version is now $new_version"
                env:
                    new_version: ${{ steps.increment-version.outputs.new-version }}
            -   name: Maven deploy
                env:
                    MAVEN_USERNAME: ${{ secrets.central_username }}
                    MAVEN_PASSWORD: ${{ secrets.central_password }}
                    MAVEN_GPG_PASSPHRASE: ${{ secrets.gpg_passphrase }}
                run: ./mvnw deploy
            -   name: Upload coverage report
                uses: actions/upload-artifact@v4
                with:
                    name: coverage-report
                    path: target/site/jacoco/
            -   name: Generate JaCoCo Badge
                uses: cicirello/jacoco-badge-generator@v2
            -   name: Commit and push the badge
                run: |
                    git add *.svg
                    git commit -m "docs(badges): update code coverage badge [skip ci]"
                    git push
