name: PR

run-name: ${{ github.actor }} is running a PR against ${{ github.head_ref || github.ref_name }} 🚀

on:
    pull_request:
        types:
            - opened
            - reopened
            - synchronize

permissions:
    contents: read

jobs:
    build:
        uses: ./.github/workflows/pr-build-workflow.yml
